##  automatically generated by configure
##  edit configure.in to change version number

const
  HPDF_MAJOR_VERSION* = 2
  HPDF_MINOR_VERSION* = 3
  HPDF_BUGFIX_VERSION* = 0
  HPDF_EXTRA_VERSION* = ""
  HPDF_VERSION_TEXT* = "2.4.6"
  HPDF_VERSION_ID* = 20406
